workflows:
  build-pwa:
    name: "Build PWA"
    environment:
      node: 14.17.0 # تأكد من استخدام إصدار Node.js المناسب
    scripts:
      - name: Install dependencies
        script: |
          npm install # تثبيت التبعيات باستخدام npm
      - name: Build PWA
        script: |
          npm run build # بناء تطبيق PWA الخاص بك
      - name: Deploy to Firebase Hosting
        script: |
          npm install -g firebase-tools
          firebase deploy --only hosting --token $FIREBASE_TOKEN # تحتاج إلى إعداد token خاص بـ Firebase
          
    artifacts:
      - build/** # تحديد المخرجات التي سيتم رفعها (إذا كان لديك مجلد بناء)

    publishing:
      email:
        recipients:
          - your-email@example.com
